node_3: "/Users/jkaloger/workspace/tac/packages/quiz/src/index.ts"
node_4: "/Users/jkaloger/workspace/tac/packages/quiz/src/do-i-need-a-car/index.ts"
node_5: "/Users/jkaloger/workspace/tac/packages/quiz/src/do-i-need-a-car/constants.ts"
node_6: "/Users/jkaloger/workspace/tac/packages/quiz/src/what-type-of-car/index.ts"
node_7: "/Users/jkaloger/workspace/tac/packages/quiz/src/what-type-of-car/constants.ts"
node_3 -> node_4: "[export]"
node_3 -> node_5: "[export]"
node_3 -> node_6: "[export]"
node_3 -> node_7: "[export]"